### ISSUE TITLE
[cetic/chart] Invalid ContainerPort definition

### ISSUE THREAD

**Issue by wiadam** [cetic/helm-swagger-ui#2]
**Describe the bug**

**Version of Helm and Kubernetes**:
K8s version: `v1.15.3`
Helm versions:
```
Client: &version.Version{SemVer:"v2.13.1", GitCommit:"618447cbf203d147601b4b9bd7f8c37a5d39fbb4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.14.3", GitCommit:"0e7f3b6637f7af8fcfddb3d2941fcc7cbebb0085", GitTreeState:"clean"}
```

**What happened**:
Deployment is failing validation because of usage of `targetPort: http` in ContainerPort section.
```
kubectl failed exit status 1: error validating data: ValidationError(Deployment.spec.template.spec.containers[0].ports[0]): unknown field "targetPort" in io.k8s.api.core.v1.ContainerPort
```

**What you expected to happen**:
Passing k8s object validation to be able to deploy
See https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.16/#containerport-v1-core for reference on allowed fields

**How to reproduce it** (as minimally and precisely as possible):
try deployment (no values.yaml override)

**Anything else we need to know**:

Proposed fix

```
diff --git a/Chart.yaml b/Chart.yaml
index a10dba2..00f051d 100644
--- a/Chart.yaml
+++ b/Chart.yaml
@@ -1,5 +1,5 @@
 name: swaggerui
-version: 0.1.0
+version: 0.1.1
 appVersion: 3.23.10
 description: Swagger is an open-source software framework backed by a large ecosystem of tools that helps developers design, build, document, and consume RESTful Web services.
 keywords:
diff --git a/templates/deployment.yaml b/templates/deployment.yaml
index 2c39752..96b42eb 100644
--- a/templates/deployment.yaml
+++ b/templates/deployment.yaml
@@ -37,7 +37,6 @@ spec:
           - name: http
             containerPort: {{ .Values.service.port }}
             protocol: TCP
-            targetPort: http
       {{- if .Values.swaggerui.jsonPath }}
       volumes:
         - name: swagger-config

```

**Comment by alexnuttinck** [comment]
Hello @wiadam, thanks for your bug report.

I have made some updates and created [a new release](https://github.com/cetic/helm-swagger-ui/releases/tag/0.2.0).

Can you have a try?

**Comment by wiadam** [comment]
Hi @alexnuttinck 

In addition to the `targetPort` issue, I ran into two other problems (that I patched locally to unblock my deployment):

1. Pod start failure due to start command:
     I'm deploying swagger-ui in a firewall controlled environment where access to internet is restricted, so following start command was preventing pod to start:
`args : {{ (printf "[\"mkdir /api-doc && wget %s -O /api-doc/openapi.json && apk update && apk add jq && jq '.servers += [{\\\"url\\\":\\\"%s\\\",\\\"description\\\":\\\"%s\\\"}]' /api-doc/openapi.json > json.tmp && mv json.tmp /api-doc/openapi.json && /usr/share/nginx/run.sh\"]" .Values.swaggerui.jsonUrl .Values.swaggerui.server.url .Values.swaggerui.server.description ) }} {{ end }}`
to unblock, I replaced by simple run cmd to do the trick:
`args : ["/usr/share/nginx/run.sh"]`

2. ClusterIP immutable:
   Since service was deployed and I changed to `clusterIP` after the fact, IP was already assigned and change was rejected by k8s (trying to replace existing IP by ""), so I make clusterIP in service spec optional, like below:
```
diff --git a/templates/service.yaml b/templates/service.yaml
index 833f74f..919a4f1 100644
--- a/templates/service.yaml
+++ b/templates/service.yaml
@@ -13,9 +13,7 @@ metadata:
 {{- end }}
 spec:
   type: "{{ .Values.service.type }}"
-  {{- if .Values.service.clusterIP }}
   clusterIP: "{{ .Values.service.clusterIP }}"
-  {{- end }}
   {{- if .Values.service.externalIPs }}
   externalIPs:
     {{- toYaml .Values.service.externalIPs | nindent 4 }}

```

thanks for you support

**Comment by SellamiRami** [comment]
Regarding the remark 2 (ClusterIP immutable), you can see here :  https://github.com/cetic/helm-swagger-ui/blob/8be01c9a1d68668c0295f138dee2fc5dc5bd7653/templates/service.yaml#L16
