### ISSUE TITLE
[cetic/swaggerui] jsonPath issue

### ISSUE THREAD

**Issue by yishaihl** [cetic/helm-swagger-ui#4]
Hey guys,
i'm trying to add 'local' jsonPath to the chart as follow:
- created local directory inside the repo chart folder called files - and there i'm 
   hosting my api_json files.
as you can see here:
https://ibb.co/vDyydBp

i'm constantly changing those files and i have helm ci/cd pipeline fot those json files to commit those changes.

i'm trying to understand how to grab those files from the helm folder 'files' i have and push them inside the container '/api-doc' (where the 'openapi.json' reside on) to be available for me to explore in the swagger-ui - using the 'jsonPath' attribute in 'values.yaml' (currently i'm using jsonUrl instead pointing to remote hosted file and when i need to swipe between api specs it's horrible...i need to copy-paste the url to the explore box).

if someone can explain me how can i copy those files inside the chart folder i created and use them with jsonPath : "" it will be really helpful.

Thanks a lot for your help.

**Comment by yishaihl** [comment]
Solved

**Comment by yevon** [comment]
How did you solve this? If I try to use a Docker add it just says that it is a read only filesystem and I cannot change anithing inside this folder
