### ISSUE TITLE
[cetic/swaggerui] helm upgrade fails with spec.clusterIP: Invalid value: "": field is immutable

### ISSUE THREAD

**Issue by kerherve** [cetic/helm-swagger-ui#6]
**Describe the bug**
When issue helm upgrade, it shows errors like, Error: UPGRADE FAILED: cannot patch "myswagger-swaggerui" with kind Service: Service "myswagger-swaggerui" is invalid: spec.clusterIP: Invalid value: "": field is immutable

**Version of Helm and Kubernetes**:
Helm version 3.1.3

**How to reproduce it** (as minimally and precisely as possible):

```
helm install myswagger cetic/swaggerui
NAME: myswagger
LAST DEPLOYED: Mon Jun  8 11:10:28 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

``` 
helm upgrade myswagger cetic/swaggerui
Error: UPGRADE FAILED: cannot patch "myswagger-swaggerui" with kind Service: Service "myswagger-swaggerui" is invalid: spec.clusterIP: Invalid value: "": field is immutable
```
**Anything else we need to know**:

A possible way, to solve this issue is to update the chart as follow (solution found here: https://banzaicloud.com/blog/helm3-the-good-the-bad-and-the-ugly/) :
```
# values.yaml
service:
  clusterIP: ""
---
# service.yaml
...
{{ if .Values.service.clusterIP }}
clusterIP: "{{ .Values.service.clusterIP }}"
{{ end }}
```

**Comment by alexnuttinck** [comment]
@kerherve Thanks for the bug report!
 It is fixed now. 
You can use v0.3.1 of the Chart.

**Comment by kerherve** [comment]
Thanks a lot, it works fine !
